#  Configuration for BookExploitFix. Check the default config for more information:
#  https://github.com/minoneer/BookExploitFix/blob/master/src/main/resources/config.yml
#
#  # This section defines the type of clickable actions which you wish to filter out.
#  # Possible values: true, false
#  filter_content:
#
#    # Removes actions which run commands for the player when clicking on the text.
#    # It is highly recommended to leave this enabled (true).
#    run_command: true
#
#    # Inserts a pre-defined command into the players chat bar but does not automatically execute it.
#    suggest_command: true
#
#    # Opens a file on the players computer. The file must already exist locally.
#    open_file: true
#
#    # Opens an URL in the players browser. Players have to confirm with the standard Minecraft prompt.
#    open_url: true
#
#  # This section defines on which player actions books are checked for illegal content
#  # Possible values: true, false
#  check_actions:
#
#    # Check content when a player creates a book. This always includes regular book signing.
#    # If ProtocolLib is enabled, the check also includes loading a book into the creative mode inventory.
#    book_creation: true
#
#    # Checks content when a player reads a book, either from their inventory or on a lectern.
#    book_reading: true
#
#  # Restricts all checks to selected worlds only. This value is optional and absent by default, which means
#  # checks are active in all worlds. An empty list or null will enable checks in all worlds as well.
#  world_whitelist:
#    - world
#    - world_nether
#    - world_the_end
#
#
#  The message to notify a player that content was filtered from their book. Set to null or ~ to disable.
#  Possible values: any string, null, ~. Supports minecraft color codes using &, e.g. &4
#  player_message: 'Illegal content was filtered from this book'

filter_content:
  run_command: true
  suggest_command: true
  open_file: true
  open_url: true

check_actions:
  book_creation: true
  book_reading: true

player_message: '&4Illegal content was filtered from this book'
